blank_issues_enabled: true
contact_links:
    - name: Questions
      url: https://github.com/joshdavham/jreadability/discussions
      about: Please ask general questions here instead of opening an issue.